// Code generated by protoc-gen-go. DO NOT EDIT.
// source: push.proto

package push

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type KickOutRequest_Reason int32

const (
	KickOutRequest_OTHER_LOGIN KickOutRequest_Reason = 0
)

var KickOutRequest_Reason_name = map[int32]string{
	0: "OTHER_LOGIN",
}

var KickOutRequest_Reason_value = map[string]int32{
	"OTHER_LOGIN": 0,
}

func (x KickOutRequest_Reason) String() string {
	return proto.EnumName(KickOutRequest_Reason_name, int32(x))
}

func (KickOutRequest_Reason) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1, 0}
}

type Response struct {
	Ts                   int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq                  int64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *Response) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type KickOutRequest struct {
	Reason               int32    `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
	Ts                   int64    `protobuf:"varint,2,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq                  int64    `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	Uid                  string   `protobuf:"bytes,4,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickOutRequest) Reset()         { *m = KickOutRequest{} }
func (m *KickOutRequest) String() string { return proto.CompactTextString(m) }
func (*KickOutRequest) ProtoMessage()    {}
func (*KickOutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{1}
}

func (m *KickOutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickOutRequest.Unmarshal(m, b)
}
func (m *KickOutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickOutRequest.Marshal(b, m, deterministic)
}
func (m *KickOutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickOutRequest.Merge(m, src)
}
func (m *KickOutRequest) XXX_Size() int {
	return xxx_messageInfo_KickOutRequest.Size(m)
}
func (m *KickOutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KickOutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KickOutRequest proto.InternalMessageInfo

func (m *KickOutRequest) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func (m *KickOutRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *KickOutRequest) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *KickOutRequest) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

type KickOutResponse struct {
	Ts                   int64    `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq                  int64    `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KickOutResponse) Reset()         { *m = KickOutResponse{} }
func (m *KickOutResponse) String() string { return proto.CompactTextString(m) }
func (*KickOutResponse) ProtoMessage()    {}
func (*KickOutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{2}
}

func (m *KickOutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KickOutResponse.Unmarshal(m, b)
}
func (m *KickOutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KickOutResponse.Marshal(b, m, deterministic)
}
func (m *KickOutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KickOutResponse.Merge(m, src)
}
func (m *KickOutResponse) XXX_Size() int {
	return xxx_messageInfo_KickOutResponse.Size(m)
}
func (m *KickOutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KickOutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KickOutResponse proto.InternalMessageInfo

func (m *KickOutResponse) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *KickOutResponse) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 推送给接收者的协议
type C2CPushRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MsgId                int64    `protobuf:"varint,4,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Ts                   int64    `protobuf:"varint,5,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq                  int64    `protobuf:"varint,6,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2CPushRequest) Reset()         { *m = C2CPushRequest{} }
func (m *C2CPushRequest) String() string { return proto.CompactTextString(m) }
func (*C2CPushRequest) ProtoMessage()    {}
func (*C2CPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{3}
}

func (m *C2CPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2CPushRequest.Unmarshal(m, b)
}
func (m *C2CPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2CPushRequest.Marshal(b, m, deterministic)
}
func (m *C2CPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2CPushRequest.Merge(m, src)
}
func (m *C2CPushRequest) XXX_Size() int {
	return xxx_messageInfo_C2CPushRequest.Size(m)
}
func (m *C2CPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2CPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2CPushRequest proto.InternalMessageInfo

func (m *C2CPushRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *C2CPushRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *C2CPushRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *C2CPushRequest) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *C2CPushRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *C2CPushRequest) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

// 推送给其他群成员消息协议
type C2GPushRequest struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Group                string   `protobuf:"bytes,3,opt,name=group,proto3" json:"group,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MsgId                int64    `protobuf:"varint,5,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Ts                   int64    `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`
	Seq                  int64    `protobuf:"varint,7,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *C2GPushRequest) Reset()         { *m = C2GPushRequest{} }
func (m *C2GPushRequest) String() string { return proto.CompactTextString(m) }
func (*C2GPushRequest) ProtoMessage()    {}
func (*C2GPushRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d1e4bfd2e9d102bb, []int{4}
}

func (m *C2GPushRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_C2GPushRequest.Unmarshal(m, b)
}
func (m *C2GPushRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_C2GPushRequest.Marshal(b, m, deterministic)
}
func (m *C2GPushRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_C2GPushRequest.Merge(m, src)
}
func (m *C2GPushRequest) XXX_Size() int {
	return xxx_messageInfo_C2GPushRequest.Size(m)
}
func (m *C2GPushRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_C2GPushRequest.DiscardUnknown(m)
}

var xxx_messageInfo_C2GPushRequest proto.InternalMessageInfo

func (m *C2GPushRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *C2GPushRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *C2GPushRequest) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *C2GPushRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *C2GPushRequest) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *C2GPushRequest) GetTs() int64 {
	if m != nil {
		return m.Ts
	}
	return 0
}

func (m *C2GPushRequest) GetSeq() int64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func init() {
	proto.RegisterEnum("push.KickOutRequest_Reason", KickOutRequest_Reason_name, KickOutRequest_Reason_value)
	proto.RegisterType((*Response)(nil), "push.Response")
	proto.RegisterType((*KickOutRequest)(nil), "push.KickOutRequest")
	proto.RegisterType((*KickOutResponse)(nil), "push.KickOutResponse")
	proto.RegisterType((*C2CPushRequest)(nil), "push.C2CPushRequest")
	proto.RegisterType((*C2GPushRequest)(nil), "push.C2GPushRequest")
}

func init() { proto.RegisterFile("push.proto", fileDescriptor_d1e4bfd2e9d102bb) }

var fileDescriptor_d1e4bfd2e9d102bb = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xdf, 0x4a, 0xc3, 0x30,
	0x14, 0x87, 0xed, 0xbf, 0xd4, 0x9e, 0x41, 0x37, 0xc2, 0x26, 0x75, 0x57, 0xa3, 0x57, 0xbb, 0x90,
	0x09, 0x1b, 0xf8, 0x02, 0x43, 0xea, 0x50, 0x9c, 0x44, 0xef, 0x87, 0x6e, 0x71, 0x2b, 0xd2, 0xa6,
	0x6b, 0x12, 0x7d, 0x04, 0x9f, 0xc2, 0x6b, 0x5f, 0x53, 0x9a, 0xa6, 0xd5, 0x56, 0x14, 0xbd, 0x3b,
	0xe7, 0xc0, 0xf7, 0xcb, 0xc7, 0xc9, 0x01, 0xc8, 0x24, 0xdf, 0x4d, 0xb2, 0x9c, 0x09, 0x86, 0xed,
	0xa2, 0x0e, 0x4f, 0xe0, 0x90, 0x50, 0x9e, 0xb1, 0x94, 0x53, 0xec, 0x83, 0x29, 0x78, 0x60, 0x8c,
	0x8c, 0xb1, 0x45, 0x4c, 0xc1, 0x71, 0x0f, 0x2c, 0x4e, 0xf7, 0x81, 0xa9, 0x06, 0x45, 0x19, 0xbe,
	0x80, 0x7f, 0x19, 0xaf, 0x9f, 0x96, 0x52, 0x10, 0xba, 0x97, 0x94, 0x0b, 0x7c, 0x04, 0x28, 0xa7,
	0xf7, 0x9c, 0xa5, 0x8a, 0x73, 0x88, 0xee, 0x74, 0x96, 0xd9, 0xce, 0xb2, 0xea, 0xac, 0x62, 0x22,
	0xe3, 0x4d, 0x60, 0x8f, 0x8c, 0xb1, 0x47, 0x8a, 0x32, 0x3c, 0x06, 0x44, 0x4a, 0xba, 0x0b, 0x9d,
	0xe5, 0xdd, 0xc5, 0x39, 0x59, 0x5d, 0x2d, 0xa3, 0xc5, 0x75, 0xef, 0x20, 0x9c, 0x41, 0xb7, 0x7e,
	0xf8, 0xcf, 0xb6, 0xaf, 0x06, 0xf8, 0xf3, 0xe9, 0xfc, 0x46, 0xf2, 0x5d, 0xa5, 0x8b, 0xc1, 0x7e,
	0xcc, 0x59, 0xa2, 0x30, 0x8f, 0xa8, 0x5a, 0x05, 0x31, 0xc5, 0x79, 0xc4, 0x14, 0x0c, 0x07, 0xe0,
	0xae, 0x59, 0x2a, 0x68, 0x2a, 0x94, 0xae, 0x47, 0xaa, 0x16, 0x0f, 0x00, 0x25, 0x7c, 0xbb, 0xd2,
	0xd6, 0x16, 0x71, 0x12, 0xbe, 0x5d, 0x6c, 0xb4, 0x89, 0xd3, 0x36, 0x41, 0x9f, 0x26, 0x6f, 0xca,
	0x24, 0xfa, 0xaf, 0x49, 0x1f, 0x9c, 0x6d, 0xce, 0x64, 0xa6, 0x3d, 0xca, 0xe6, 0xab, 0x9f, 0xfd,
	0x93, 0x9f, 0xf3, 0xdd, 0x0f, 0xb5, 0xfd, 0xdc, 0xda, 0x6f, 0xfa, 0x6e, 0x40, 0xa7, 0x90, 0xbb,
	0xa5, 0xf9, 0x73, 0xbc, 0xa6, 0xf8, 0x0c, 0x5c, 0xbd, 0x6e, 0xdc, 0x9f, 0xa8, 0x9b, 0x69, 0x7e,
	0xfb, 0x70, 0xd0, 0x9a, 0xea, 0x3f, 0x39, 0x05, 0x57, 0x2f, 0xbc, 0xe2, 0x9a, 0xfb, 0x1f, 0xfa,
	0xe5, 0xb4, 0x09, 0x44, 0x4d, 0x20, 0xfa, 0x05, 0x78, 0x40, 0xea, 0x78, 0x67, 0x1f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xf7, 0x1b, 0xb4, 0x98, 0xca, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PushServiceClient is the client API for PushService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PushServiceClient interface {
	KickOut(ctx context.Context, in *KickOutRequest, opts ...grpc.CallOption) (*KickOutResponse, error)
	C2CPush(ctx context.Context, in *C2CPushRequest, opts ...grpc.CallOption) (*Response, error)
	C2GPush(ctx context.Context, in *C2GPushRequest, opts ...grpc.CallOption) (*Response, error)
}

type pushServiceClient struct {
	cc *grpc.ClientConn
}

func NewPushServiceClient(cc *grpc.ClientConn) PushServiceClient {
	return &pushServiceClient{cc}
}

func (c *pushServiceClient) KickOut(ctx context.Context, in *KickOutRequest, opts ...grpc.CallOption) (*KickOutResponse, error) {
	out := new(KickOutResponse)
	err := c.cc.Invoke(ctx, "/push.PushService/KickOut", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) C2CPush(ctx context.Context, in *C2CPushRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/push.PushService/C2CPush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pushServiceClient) C2GPush(ctx context.Context, in *C2GPushRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/push.PushService/C2GPush", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PushServiceServer is the server API for PushService service.
type PushServiceServer interface {
	KickOut(context.Context, *KickOutRequest) (*KickOutResponse, error)
	C2CPush(context.Context, *C2CPushRequest) (*Response, error)
	C2GPush(context.Context, *C2GPushRequest) (*Response, error)
}

// UnimplementedPushServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPushServiceServer struct {
}

func (*UnimplementedPushServiceServer) KickOut(ctx context.Context, req *KickOutRequest) (*KickOutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KickOut not implemented")
}
func (*UnimplementedPushServiceServer) C2CPush(ctx context.Context, req *C2CPushRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method C2CPush not implemented")
}
func (*UnimplementedPushServiceServer) C2GPush(ctx context.Context, req *C2GPushRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method C2GPush not implemented")
}

func RegisterPushServiceServer(s *grpc.Server, srv PushServiceServer) {
	s.RegisterService(&_PushService_serviceDesc, srv)
}

func _PushService_KickOut_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KickOutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).KickOut(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.PushService/KickOut",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).KickOut(ctx, req.(*KickOutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_C2CPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2CPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).C2CPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.PushService/C2CPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).C2CPush(ctx, req.(*C2CPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PushService_C2GPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(C2GPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PushServiceServer).C2GPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/push.PushService/C2GPush",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PushServiceServer).C2GPush(ctx, req.(*C2GPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PushService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "push.PushService",
	HandlerType: (*PushServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "KickOut",
			Handler:    _PushService_KickOut_Handler,
		},
		{
			MethodName: "C2CPush",
			Handler:    _PushService_C2CPush_Handler,
		},
		{
			MethodName: "C2GPush",
			Handler:    _PushService_C2GPush_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "push.proto",
}
